const ActionTypes = {
    CHANGE_NEW_EXPERIMENT_TEXT: 'CHANGE_NEW_EXPERIMENT_TEXT',

    CREATE_EXPERIMENT_REQUEST: 'CREATE_EXPERIMENT_REQUEST',
    CREATE_EXPERIMENT_FAIL: 'CREATE_EXPERIMENT_FAIL',
    CREATE_EXPERIMENT_SUCCESS: 'CREATE_EXPERIMENT_SUCCESS',
}

export default ActionTypes;
