const ActionTypes = {
    CHANGE_NEW_EXPERIMENT_TEXT: 'CHANGE_NEW_EXPERIMENT_TEXT',

    CREATE_EXPERIMENT_REQUEST: 'CREATE_EXPERIMENT_REQUEST',
    CREATE_EXPERIMENT_FAIL: 'CREATE_EXPERIMENT_FAIL',
    CREATE_EXPERIMENT_SUCCESS: 'CREATE_EXPERIMENT_SUCCESS',

    CREATE_FOLDER_REQUEST: 'CREATE_FOLDER_REQUEST',
    CREATE_FOLDER_FAIL: 'CREATE_FOLDER_FAIL',
    CREATE_FOLDER_SUCCESS: 'CREATE_FOLDER_SUCCESS',

    UPDATE_FOLDER_REQUEST: 'UPDATE_FOLDER_REQUEST',
    UPDATE_FOLDER_FAIL: 'UPDATE_FOLDER_FAIL',
    UPDATE_FOLDER_SUCCESS: 'UPDATE_FOLDER_SUCCESS',

    CHANGE_NEW_FOLDER_TEXT: 'CHANGE_NEW_FOLDER_TEXT',
    CHANGE_UPDATE_FOLDER_TEXT: 'CHANGE_UPDATE_FOLDER_TEXT',

    UPDATE_LATEST_MEASUREMENT: 'UPDATE_LATEST_MEASUREMENT', 
    UPDATE_IS_ALIVE: 'UPDATE_IS_ALIVE', 

    LOCATION_CHANGE: 'LOCATION_CHANGE',
    CREATE_NEW_TRIAL: 'CREATE_NEW_TRIAL',
    CREATE_NEW_MEASUREMENT: 'CREATE_NEW_MEASUREMENT',

    CHANGE_TRIAL_FILTER: 'CHANGE_TRIAL_FILTER',
    CLEAR_TRIALS: 'CLEAR_TRIALS',

    CREATE_NEW_FOLDER: 'CREATE_NEW_FOLDER',
    ADD_TRIAL_TO_FOLDER: 'ADD_TRIAL_TO_FOLDER',
    CHANGE_FOLDER_FILTER: 'CHANGE_FOLDER_FILTER',
    CLEAR_FOLDERS: 'CLEAR_FOLDERS',
}

export default ActionTypes;
